### ISSUE TITLE
Unable to save prefab

### ISSUE THREAD

**Issue by Joscho2** [johannesugb/VolumetricLinesUnity#8] opened 2021-02-24 22:38 UTC
It is unable to save shader properties. Only in some random constelation in some random time it is possible to save volumetric line.
![obrázok](https://user-images.githubusercontent.com/26082615/109075416-5f231100-76f9-11eb-86d1-08edc0a29294.png)

**Comment by johannesugb** [comment] 2021-02-25 07:41
How can the problem be reproduced?

**Comment by johannesugb** [comment] 2021-09-05 11:53
Haven't seen this problem reported elsewhere and since there hasn't been any reply since Feb 25, closing this now.

**Closed as completed by johannesugb** 2021-09-05 11:53 UTC
