### ISSUE TITLE
Error on leaving play mode

### ISSUE THREAD

**Issue by insominx** [johannesugb/VolumetricLinesUnity#7] opened 2020-05-12 23:45 UTC
Using Unity 2019.3.9 with URP I get the following when leaving play mode:

`Destroying assets is not permitted to avoid data loss.
If you really want to remove an asset use DestroyImmediate (theObject, true);
UnityEngine.Object:DestroyImmediate(Object)
VolumetricLines.VolumetricLineBehavior:DestroyMaterial() (at Assets/Plugins/VolumetricLines/Scripts/VolumetricLineBehavior.cs:223)
VolumetricLines.VolumetricLineBehavior:OnDestroy() (at Assets/Plugins/VolumetricLines/Scripts/VolumetricLineBehavior.cs:382)`

**Comment by johannesugb** [comment] 2020-05-17 22:45
Thanks for reporting this issue. Unfortunately, I am unable to reproduce this problem (using Unity 2019.3.14 a.t.m.)

May I ask you to describe the steps to reproduce this problem precisely?
A screenshot of the _Inspector_-View would be very helpful, too.

**Comment by johannesugb** [comment] 2021-09-05 11:54
Any more details about this problem?     
Has the problem re-occured?  

If no further details are reported, I'll close this issue, assuming that the problem is gone.

**Closed as completed** 2023-07-03 08:21 UTC
